### ISSUE TITLE
release v1.0.0

### ISSUE THREAD

**Issue by zhengchun** [fastbootstrap/atlassian-design-for-bootstrap#1]
![fastbootstrap component preview](https://user-images.githubusercontent.com/5097328/193053703-191d5d62-ac30-4d2c-b7a0-c6b00b17a9e0.png)

Ready for your project and feedback!

**Comment by emotality** [comment]
Looks dope 🥹

Would love to use this in production, but would this be maintained or would we need to go back to BS in the future? 🙈
Does this answer depend on contributors, or would you be happy to continue alone?

Any plans for BS 5.3 (dark themes etc)?

Thanks! ✌🏻

**Comment by pfk84** [comment]
Also really love the looks, very clean and reduced! Currently trying it on a project but I was wondering the same as @emotality ...

**Comment by zhengchun** [comment]
Yes ,it will supports BS 5.3, including dark mode.

**Comment by pfk84** [comment]
Wonderful!

**Comment by zhengchun** [comment]
Released v2.0.0
