### ISSUE TITLE
Cannot found 'fastboostrap.js' in dist

### ISSUE THREAD

**Issue by AchievedOwner** [fastbootstrap/atlassian-design-for-bootstrap#22]
I saw in git history that `fastbootstrap.js` had been removed. It means there is no longer to use this script any more in future, right?

**Comment by zhengchun** [comment]
`fastbootstrap.js` file has been removed, and is no longer used even in future. I recommend using Bootstrap official JS file.

Without JS, I could update the fastbootstrap theme as soon as when bootstrap 6.0 released.
