### ISSUE TITLE
Correct version name

### ISSUE THREAD

**Issue by paulocoutinhox** [fastbootstrap/atlassian-design-for-bootstrap#28]
Hi,

What is the correct version from release?

I downloaded 2.2.0 but inside it is:

```
@charset "UTF-8";/*! FastBootstrap v2.1 (https://fastbootstrap.com)
```

**Comment by zhengchun** [comment]
`2.2.0` is the latest version, `/*! FastBootstrap v2.1 (https://fastbootstrap.com)` is a comment in SCSS file header, just missing fix.
